<a href="https://colab.research.google.com/github/limjs0108/ai/blob/master/Crawling_NaverMovie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests

In [2]:
from bs4 import BeautifulSoup as bs

In [3]:
import pandas

In [5]:
html = requests.get('https://movie.naver.com/movie/sdb/rank/rmovie.naver')

In [6]:
soup = bs(html.text)

In [9]:
len(soup.select('tr > td.title'))

50

In [11]:
movies = soup.select('tr > td.title')
movies[0]

<td class="title">
<div class="tit3">
<a href="/movie/bi/mi/basic.naver?code=191547" title="나일 강의 죽음">나일 강의 죽음</a>
</div>
</td>

In [13]:
title = movies[0].select('div.tit3 > a')[0].text
title

'나일 강의 죽음'

In [14]:
movie_data = []
rank = 1
for movie in movies:
  title = movie.select('div.tit3 > a')[0].text
  movie_data.append([rank, title])
  rank += 1

movie_data

[[1, '나일 강의 죽음'],
 [2, '나의 촛불'],
 [3, '언차티드'],
 [4, '해적: 도깨비 깃발'],
 [5, '킹메이커'],
 [6, '355'],
 [7, '인민을 위해 복무하라'],
 [8, '킹스맨: 퍼스트 에이전트'],
 [9, '스파이더맨: 노 웨이 홈'],
 [10, '모럴센스'],
 [11, '극장판 주술회전 0'],
 [12, '리코리쉬 피자'],
 [13, '안테벨룸'],
 [14, '특송'],
 [15, '더 배트맨'],
 [16, '스크림'],
 [17, '굿 보스'],
 [18, '이상한 나라의 수학자'],
 [19, '씽2게더'],
 [20, '대한민국 대통령'],
 [21, '타짜 전설의 땁'],
 [22, '하우스 오브 구찌'],
 [23, '전투왕'],
 [24, '나이트메어 앨리'],
 [25, '만년이 지나도 변하지 않는 게 있어'],
 [26, '듄'],
 [27, '극장판 안녕 자두야: 제주도의 비밀'],
 [28, '미싱타는 여자들'],
 [29, '경관의 피'],
 [30, '리프레쉬'],
 [31, '피그'],
 [32, '셰터드'],
 [33, '시크릿 카운터'],
 [34, '문폴'],
 [35, '쥬라기 월드: 도미니언'],
 [36, '시라노'],
 [37, '닥터 스트레인지: 대혼돈의 멀티버스'],
 [38, '역으로 가는 길을 알려줘'],
 [39, '장르만 로맨스'],
 [40, '오리엔트 특급 살인'],
 [41, '더 마더'],
 [42, '드라이브 마이 카'],
 [43, '극장판 바다 탐험대 옥토넛 : 해저동굴 대탈출'],
 [44, '어나더 라운드'],
 [45, '뜨거운 피'],
 [46, '코만도'],
 [47, '코로나'],
 [48, '그린 북'],
 [49, '아웃브레이크 호텔'],
 [50, 'B컷']]

In [15]:
import pandas as pd

df = pd.DataFrame(movie_data, columns = ['순위', '타이틀'])
df

    순위                        타이틀
0    1                   나일 강의 죽음
1    2                      나의 촛불
2    3                       언차티드
3    4                 해적: 도깨비 깃발
4    5                       킹메이커
5    6                        355
6    7                인민을 위해 복무하라
7    8              킹스맨: 퍼스트 에이전트
8    9              스파이더맨: 노 웨이 홈
9   10                       모럴센스
10  11                 극장판 주술회전 0
11  12                    리코리쉬 피자
12  13                       안테벨룸
13  14                         특송
14  15                      더 배트맨
15  16                        스크림
16  17                       굿 보스
17  18                이상한 나라의 수학자
18  19                       씽2게더
19  20                   대한민국 대통령
20  21                   타짜 전설의 땁
21  22                  하우스 오브 구찌
22  23                        전투왕
23  24                   나이트메어 앨리
24  25        만년이 지나도 변하지 않는 게 있어
25  26                          듄
26  27        극장판 안녕 자두야: 제주도의 비밀
27  28                   미싱타는 여자들
28  29                      경관의 피
29  30                       리프레쉬
30  31                         피그
31  32                        셰터드
32  33                    시크릿 카운터
33  34                         문폴
34  35               쥬라기 월드: 도미니언
35  36                        시라노
36  37        닥터 스트레인지: 대혼돈의 멀티버스
37  38              역으로 가는 길을 알려줘
38  39                    장르만 로맨스
39  40                 오리엔트 특급 살인
40  41                       더 마더
41  42                  드라이브 마이 카
42  43  극장판 바다 탐험대 옥토넛 : 해저동굴 대탈출
43  44                    어나더 라운드
44  45                      뜨거운 피
45  46                        코만도
46  47                        코로나
47  48                       그린 북
48  49                  아웃브레이크 호텔
49  50                         B컷

In [16]:
df.to_excel('Naver_movies.xlsx',index=False)